# Generated by Django 4.0.6 on 2022-08-26 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True, verbose_name='start_date')),
                ('end_date', models.DateTimeField(null=True, verbose_name='end_date')),
                ('in_progress', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(null=True, verbose_name='start')),
                ('end', models.DateTimeField(null=True, verbose_name='end')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('preferred_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(null=True, verbose_name='start')),
                ('end', models.DateTimeField(null=True, verbose_name='end')),
                ('volunteer', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('client', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api.case')),
                ('session', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api.session')),
            ],
        ),
    ]
